// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCq1HaXOmihXE7jxf8o78AnZPo17DwROM',
    appId: '1:1050691041527:web:0bff924b3c8dfc4d9abbf2',
    messagingSenderId: '1050691041527',
    projectId: 'presence-app-71bed',
    authDomain: 'presence-app-71bed.firebaseapp.com',
    storageBucket: 'presence-app-71bed.appspot.com',
    measurementId: 'G-K7V4B7K9SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_fPMsKR_K6P4PFvj29QrHl_FDIcWLF4',
    appId: '1:1050691041527:android:58b62e9a78f6ceff9abbf2',
    messagingSenderId: '1050691041527',
    projectId: 'presence-app-71bed',
    storageBucket: 'presence-app-71bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAetI1cOoXIhpfIkz3rskdhSpUaK3PWKDE',
    appId: '1:1050691041527:ios:479cfb5aa29f3feb9abbf2',
    messagingSenderId: '1050691041527',
    projectId: 'presence-app-71bed',
    storageBucket: 'presence-app-71bed.appspot.com',
    iosClientId: '1050691041527-8q100s6sd3e7kvjt84oipr0bjkdultpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAetI1cOoXIhpfIkz3rskdhSpUaK3PWKDE',
    appId: '1:1050691041527:ios:479cfb5aa29f3feb9abbf2',
    messagingSenderId: '1050691041527',
    projectId: 'presence-app-71bed',
    storageBucket: 'presence-app-71bed.appspot.com',
    iosClientId: '1050691041527-8q100s6sd3e7kvjt84oipr0bjkdultpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );
}
