name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  firebase_storage: ^11.0.3
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  lottie: ^1.4.3
  responsive_framework: ^0.2.0
  get_it: ^7.2.0
  shimmer: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
